version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.7.28-management
    container_name: rabbitmq
    volumes:
      - ./vol/rabbitmq/conf:/etc/rabbitmq/
      - ./vol/rabbitmq/data/:/var/lib/rabbitmq/
      - ./vol/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      # RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-secret_cookie}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    ports:
      - 5672:5672 #amqp
      - 15672:15672 #http
      - 15692:15692 #prometheus
    # healthcheck:
    # test: [ "CMD", "rabbitmqctl", "status"]
    # interval: 5s
    # timeout: 20s
    # retries: 5
