name: MkDocs Build

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18      
      - name: Install requirements
        run: |
          npm install uglifycss -g
          pip install -r requirements.txt
      - name: Build and deploy
        working-directory: .
        run: mkdocs gh-deploy --force --clean --verbose

